version: '3.3'

services:
    app:
        build: .
        command: npm start
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/backend_plant_care
        links:
            - db
    db:
        image: mysql:5.7
        ports:
            - 3308:3306
        expose:
            - "3308"
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_USER:  root
            MYSQL_ROOT_PASSWORD: root
        